### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Ev87** [rentmanpublic/rentalshop#11]
I'm using the plugin here in Italy and as it was in Dutch language (I don't know why if the English translation is available too) I edited the English file and translated in Italian.
MIght i know if I can send it so you can add the translation?

Thanks

**Comment by Olaf551** [comment]
Hi! The default language is Dutch and the plugin will switch to English if your Wordpress is set to English and to German if Wordpress is set to German.
Thank you for making an Italian translation! I will add it to the next version of the plugin. Can you send it to this address: olaf@rentman.nl
